<?php

  $labels = [
    'name'                     => esc_html__( 'Cars', 'wpfc-cars' ),
    'singular_name'            => esc_html__( 'Car', 'wpfc-cars' ),
    'add_new'                  => esc_html__( 'Add New', 'wpfc-cars' ),
    'add_new_item'             => esc_html__( 'Add new car', 'wpfc-cars' ),
    'edit_item'                => esc_html__( 'Edit Car', 'wpfc-cars' ),
    'new_item'                 => esc_html__( 'New Car', 'wpfc-cars' ),
    'view_item'                => esc_html__( 'View Car', 'wpfc-cars' ),
    'view_items'               => esc_html__( 'View Cars', 'wpfc-cars' ),
    'search_items'             => esc_html__( 'Search Cars', 'wpfc-cars' ),
    'not_found'                => esc_html__( 'No cars found', 'wpfc-cars' ),
    'not_found_in_trash'       => esc_html__( 'No cars found in Trash', 'wpfc-cars' ),
    'parent_item_colon'        => esc_html__( 'Parent Car:', 'wpfc-cars' ),
    'all_items'                => esc_html__( 'All Cars', 'wpfc-cars' ),
    'archives'                 => esc_html__( 'Car Archives', 'wpfc-cars' ),
    'attributes'               => esc_html__( 'Car Attributes', 'wpfc-cars' ),
    'insert_into_item'         => esc_html__( 'Insert into car', 'wpfc-cars' ),
    'uploaded_to_this_item'    => esc_html__( 'Uploaded to this car', 'wpfc-cars' ),
    'featured_image'           => esc_html__( 'Featured image', 'wpfc-cars' ),
    'set_featured_image'       => esc_html__( 'Set featured image', 'wpfc-cars' ),
    'remove_featured_image'    => esc_html__( 'Remove featured image', 'wpfc-cars' ),
    'use_featured_image'       => esc_html__( 'Use as featured image', 'wpfc-cars' ),
    'menu_name'                => esc_html__( 'Cars', 'wpfc-cars' ),
    'filter_items_list'        => esc_html__( 'Filter cars list', 'wpfc-cars' ),
    'items_list_navigation'    => esc_html__( 'Cars list navigation', 'wpfc-cars' ),
    'items_list'               => esc_html__( 'Cars list', 'wpfc-cars' ),
    'item_published'           => esc_html__( 'Car published', 'wpfc-cars' ),
    'item_published_privately' => esc_html__( 'Car published privately', 'wpfc-cars' ),
    'item_reverted_to_draft'   => esc_html__( 'Car reverted to draft', 'wpfc-cars' ),
    'item_scheduled'           => esc_html__( 'Car scheduled', 'wpfc-cars' ),
    'item_updated'             => esc_html__( 'Car updated', 'wpfc-cars' ),
    'text_domain'              => esc_html__( 'wpfc-cars', 'wpfc-cars' ),
  ];
  $args = [
    'label'               => esc_html__( 'Cars', 'wpfc-cars' ),
    'labels'              => $labels,
    'description'         => '',
    'public'              => true,
    'hierarchical'        => false,
    'exclude_from_search' => false,
    'publicly_queryable'  => true,
    'show_ui'             => true,
    'show_in_nav_menus'   => true,
    'show_in_admin_bar'   => true,
    'show_in_rest'        => true,
    'menu_position'       => 20,
    'query_var'           => true,
    'can_export'          => true,
    'delete_with_user'    => true,
    'has_archive'         => true,
    'rest_base'           => '',
    'show_in_menu'        => true,
    'menu_icon'           => 'dashicons-admin-network',
    'capability_type'     => 'post',
    'supports'            => ['title', 'editor', 'thumbnail'],
    'taxonomies'          => ['elementor_library_category'],
    'rewrite'             => [
      'with_front' => false,
    ],
  ];

  register_post_type( 'car', $args );
